version: '3.8'
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,sqs,lambda,logs
      - DYNAMODB_SHARE_DB=1
      - DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # ───────────────────────────────────────────────────────────
  # 로컬용 PostgreSQL 14
  postgres:
    image: postgres:14
    container_name: pg14_local
    restart: unless-stopped
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      # 컨테이너 초기화 시 여기에 있는 .sql을 실행하여 스키마 생성
      - ./postgres/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U local" ]
      interval: 5s
      retries: 5
  # ───────────────────────────────────────────────────────────

  terraform-run:
    image: hashicorp/terraform:1.5.2
    container_name: terraform-run
    volumes:
      - ./terraform:/terraform  # Terraform 설정 파일(main.tf, provider.tf 등)
      - ../app/dist:/dist        # Lambda zip 파일 위치
    working_dir: /terraform
    entrypoint: [
      "sh",
      "-c",
      "terraform init && terraform destroy -auto-approve && terraform apply -auto-approve"
    ]
    restart: "no"
